---

- name: Converge
  hosts: all

#############
# Pre_tasks #
#############

  pre_tasks:
    - include_role:
        name: manala.
      vars:
        manala_apt_preferences:

#########
# Tasks #
#########

  tasks:
    - include_role:
        name: manala.
      vars:
