---

- name: Converge
  hosts: all

#############
# Pre_tasks #
#############

  pre_tasks:
    - include_role:
        name: manala.apt
      vars:
        manala_apt_preferences:
          - vault@manala

#########
# Tasks #
#########

  tasks:
    - include_role:
        name: manala.vault
      vars:
        manala_vault_config_template: fixtures/config.j2
