---

- name: Converge
  hosts: all

############
# Pre_task #
############

  pre_tasks:
    - apt:
        name:
          - ssh
          - rsync
        install_recommends: false
        update_cache: true

########
# Task #
########

  tasks:
    - include_role:
        name: manala.deploy
      vars:
        manala_deploy_dir: /tmp/app
        manala_deploy_strategy: synchronize
        manala_deploy_strategy_synchronize_src: "{{ playbook_dir ~ '/fixtures/app/' }}"
        manala_deploy_removed:
          - file
          - dir
