---

- name: Converge
  hosts: all

#############
# Pre_tasks #
#############

  pre_tasks:
    - include_role:
        name: manala.apt
      vars:

#########
# Tasks #
#########

  tasks:
    - include_role:
        name: manala.
      vars:
