---

package:
  maxscale:
    installed: true

command:
  maxscale --version:
    exit-status: 0
    stdout:
      - "/^MaxScale 2.0.\\d+$/"
  sudo maxadmin show users:
    exit-status: 0
    stdout:
      - "/^Enabled Linux accounts \\(secure\\)    : $/"
      - "/^Created network accounts \\(insecure\\): foo, bar$/"

file:
  /etc/maxscale.cnf.test:
    exists:   true
    filetype: file
    contains:
      - "[maxscale]"
      - threads = auto
      - "[Splitter Service]"
      - type = service
      - router = readwritesplit
      - servers = mariadb-1, mariadb-2, mariadb-3
      - user = maxscale
      - passwd = XXXXXXXXXXXX
  /var/lib/maxscale/passwd:
    exists:   true
    filetype: file
    contains:
      - foo:$1$MXS$ilOCSZPnjmHjTz6B96SiJ1
      - bar:$1$MXS$M.YZOr2pNTgW87l7KQWLU/
  /var/lib/maxscale/passwd.test:
    exists: true
    filetype: file
    size: 0

service:
  maxscale:
    enabled: true
    running: true
