---

- name: Converge
  hosts: all

#############
# Pre_tasks #
#############

  pre_tasks:
    - include_role:
        name: manala.apt
      vars:
        manala_apt_preferences:
          - maxscale@maxscale_2_3

#########
# Tasks #
#########

  tasks:
    - include_role:
        name: manala.maxscale
      vars:
        manala_maxscale_config_file: /etc/maxscale.cnf.test
        manala_maxscale_config:
          - maxscale:
            - threads: auto #Dedicated container
          - Splitter Service:
            - type:    service
            - router:  readwritesplit
            - servers: mariadb-1, mariadb-2, mariadb-3
            - user:    maxscale
            - passwd:  XXXXXXXXXXXX
        manala_maxscale_configs_dir: /etc/maxscale.cnf.d.test
        manala_maxscale_configs:
          - file: foo.cnf
            config:
              - foo-1:
                - type: server
                - address: foo-1
                - port: 3306
                - protocol: MariaDBBackend
          - file: bar.cnf
            state: present
          - file: baz.cnf
            state: absent
        manala_maxscale_network_users:
          - name:     foo
            password: $1$MXS$ilOCSZPnjmHjTz6B96SiJ1 # "foo"
          - name:     bar
            password: $1$MXS$M.YZOr2pNTgW87l7KQWLU/ # "bar"

    - include_role:
        name: manala.maxscale
      vars:
        manala_maxscale_configs_dir: /etc/maxscale.cnf.d.test
        manala_maxscale_configs:
          - file: bar.cnf
            state: absent
          - file: baz.cnf
            state: present
        manala_maxscale_users_file:  /var/lib/maxscale/passwd.test
        manala_maxscale_network_users: []

    - include_role:
        name: manala.maxscale
      vars:
        manala_maxscale_configs_dir: /etc/maxscale.cnf.d.exclusive
        manala_maxscale_configs:
          - file: foo.cnf
          - file: bar.cnf
          - file: baz.cnf

    - include_role:
        name: manala.maxscale
      vars:
        manala_maxscale_configs_dir: /etc/maxscale.cnf.d.exclusive
        manala_maxscale_configs_exclusive: true
        manala_maxscale_configs:
          - file: bar.cnf
