---

- name: Converge
  hosts: all

############
# Pre_task #
############

  pre_tasks:
    - include_role:
        name: manala.apt
      when: ansible_distribution_release in ['jessie', 'stretch']
      vars:
        manala_apt_preferences:
          - hugo@manala

########
# Task #
########

  tasks:
    - include_role:
        name: manala.hugo
