---

- name: Converge
  hosts: all

########
# Task #
########

  tasks:
    - include_role:
        name: manala.beanstalkd
      vars:
        manala_beanstalkd_config_file: /etc/default/beanstalkd.test
        manala_beanstalkd_config:
          - BEANSTALKD_LISTEN_PORT: 12345
