---

- name: Converge
  hosts: all

#############
# Pre_tasks #
#############

  pre_tasks:
    - include_role:
        name: manala.apt
      vars:
        manala_apt_preferences:
          - php@sury_php
        manala_apt_repositories:
          - blackfire
        manala_apt_packages:
          - php7.2-cgi  # Sapi
          - php7.2-tidy # Native extension
          - php-apcu    # Pecl extension
          - php7.2-cli
          - php7.2-fpm
          - php-uuid
        install_recommends: false
    - copy:
        dest:    /etc/php/7.2/cli/conf.d/baz.ini
        content: |
          memory_limit = 255M
    - copy:
        dest:    /etc/php/7.2/fpm/conf.d/baz.ini
        content: |
          memory_limit = 257M
    - copy:
        dest:    /etc/php/7.2/fpm/pool.d/bar.conf
        content: |
          ; Foo
    - command: phpdismod uuid

#########
# Tasks #
#########

  tasks:
    - include_role:
        name: manala.php
      vars:
        manala_php_version: 7.2
        manala_php_sapis:
          - cli
          - sapi:  fpm
            state: present
          - sapi:  cgi
            state: absent
        manala_php_extensions:
          - date     # Embedded extension
          - mbstring # Embedded extension
          - intl     # Native extension
          - geoip    # Pecl extension
          - xml
          # Native extension present/enabled
          - extension: curl
            state:     present
          - extension: gd
            enabled:   true
          # Native extension absent/disabled
          - extension: tidy
            state:     absent
          - extension: json
            enabled:   false
          # Pecl extension present/enabled
          - extension: apcu
            state:     present
          - extension: gmagick
            enabled:   true
          # Pecl extension absent/disabled
          - extension: gearman
            state:     absent
          - extension: xdebug
            enabled:   false
          # Pecl extension present & disabled
          - extension: uuid
            state:     present
        manala_php_configs_exclusive: true
        manala_php_configs:
          - file: foo.ini
            config:
              - memory_limit: 123M
          - file: foo.ini
            config:
              - memory_limit: 456M
          - file:     bar.ini
            template: configs/app.dev.j2
            config:
              - memory_limit: 256M
        manala_php_cli_configs:
          - file:     bar.ini
            template: configs/app.dev.j2
            config:
              - memory_limit: 255M
        manala_php_fpm_configs:
          - file:     bar.ini
            template: configs/app.dev.j2
            config:
              - memory_limit: 257M
        manala_php_fpm_pools_exclusive: true
        manala_php_fpm_pools:
          - file:     www.conf
            template: fpm_pools/default.j2
            config:
              - www:
                - pm.max_children: 12
          - file:     foo.conf
            template: fpm_pools/default.j2
            config:
              - foo:
                - listen: /run/php-fpm.foo.sock
                - env[_FOO]: bar
                - env[_BAR]: 123
                - env:
                    FOO: bar
                    BAR: 123
                    BAZ: 1.2
                    QUX: foo=bar
        manala_php_blackfire: true
        manala_php_blackfire_agent_config:
          - server-id: c74906db-43d3-4c96-ab27-010600321b89
          - server-token: 5b78cc7fea3b766ff4ea470178b502c829c09d58ebdc20252e0337db804000e2
        manala_php_blackfire_client_config:
          - client-id: b7bf7d2d-c8c1-4354-82bf-aa403afbc3b3
          - client-token: e7d9ca7e486b67d1f2d9b764fb383340fbd374e20daefa747e8a4fd690d83e7b
        manala_php_applications:
          - phpcs
          - phpunit@4.8.30
          - application: phpunit
            version: 5.7.25
