---

- name: Converge
  hosts: all

############
# Pre_task #
############

  pre_tasks:
    - apt:
        name:
          - ssh
          - rsync
        install_recommends: false
        update_cache: true

########
# Task #
########

  tasks:
    - include_role:
        name: manala.deploy
      vars:
        manala_deploy_dir: /tmp/app
        manala_deploy_strategy: include
        manala_deploy_strategy_include_name: "{{ playbook_dir ~ '/fixtures/strategy/include.yml' }}"
        manala_deploy_strategy_include_options:
          filename: strategy_include.txt
