---

- name: Converge
  hosts: all

#############
# Pre_tasks #
#############

  pre_tasks:
    - include_role:
        name: manala.apt
      vars:
        manala_apt_preferences:
          - elasticsearch@elasticsearch_1_5
          - openjdk@backports
        manala_apt_packages:
          - openjdk-8-jre-headless

#########
# Tasks #
#########

  tasks:
    - include_role:
        name: manala.elasticsearch
      vars:
        manala_elasticsearch_config:
          - node.name: Foo Bar
        manala_elasticsearch_environment_file: /etc/default/elasticsearch.test
        manala_elasticsearch_environment:
          - ES_JAVA_OPTS: -Xms1g -Xmx1g
        manala_elasticsearch_plugins:
          - "mobz/elasticsearch-head"

##############
# Post_tasks #
##############


  post_tasks:
    - name: Post tasks > Wait for pretty response
      uri:
        url: http://localhost:9200/?pretty
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
