---

- name: Converge
  hosts: all

#############
# Pre_tasks #
#############

  pre_tasks:
    - include_role:
        name: manala.apt
      vars:
        manala_apt_preferences:
          - nodejs@nodesource_4

#########
# Tasks #
#########

  tasks:
    - include_role:
        name: manala.nodejs
